avluis/Hentoid

- app/src/main/java/me/devsaki/hentoid/HentoidApp.java
- app/src/main/res/layout/include_row_details.xml
- app/src/main/res/layout/row_queue.xml
thumbnails previously had constant height, was cropped, and centered.
thumbnails now have variable height, is not transformed, and fit to view width
> Fix thumbnail UX bug

- app/src/main/java/me/devsaki/hentoid/util/FileUtil.java
- app/src/main/java/me/devsaki/hentoid/util/Helper.java
- app/src/main/res/layout/item_queue.xml
- Fix crashes & odd behaviours (e.g. creating one folder per page) when using old installs with capitalized folder names (e.g. Tsumino instead of tsumino)
- Fix queue item display bug
> Fix crashes & odd behaviours on installs with capitalized folder names + queue item display bug

- app/src/main/java/me/devsaki/hentoid/abstracts/DownloadsFragment.java
- app/src/main/java/me/devsaki/hentoid/activities/AboutActivity.java
- app/src/main/java/me/devsaki/hentoid/activities/websites/BaseWebActivity.java
- app/src/main/java/me/devsaki/hentoid/activities/websites/TsuminoActivity.java
- app/src/main/java/me/devsaki/hentoid/database/constants/ContentTable.java
- app/src/main/java/me/devsaki/hentoid/database/domains/Content.java
- app/src/main/java/me/devsaki/hentoid/fragments/QueueFragment.java
- app/src/main/java/me/devsaki/hentoid/services/ContentDownloadService.java
- app/src/main/java/me/devsaki/hentoid/services/ContentQueueManager.java
- app/src/main/java/me/devsaki/hentoid/services/InputStreamVolleyRequest.java
- app/src/main/java/me/devsaki/hentoid/services/RequestQueueManager.java
- app/src/main/java/me/devsaki/hentoid/util/FileHelper.java
- app/src/main/java/me/devsaki/hentoid/util/FileUtil.java
- app/src/main/java/me/devsaki/hentoid/util/NetworkStatus.java
- app/src/main/java/me/devsaki/hentoid/util/VolleyOkHttp3Stack.java
- app/src/main/res/layout/intro_slide_02_alt.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/strings_slides.xml
- Fix out of memory errors during download caused by improper initialization of OkHttpClient
- Fix image downloads slowing down / freezing main thread 
- Fix crash when importing a book without any attributes in its JSON 
- Fix error when exporting book as ZIP archive
- Prevent the queue from being displayed as active when there are books left to download at app startup
- Fix wrong content (ad) filter for Tsumino
- Fix rare crash when turning device orientation while typing on nHentai search bar (thanks Cat Knight)
- Extend timeout delay for network connectivity check
> Stability fixes from beta test

- app/src/main/java/me/devsaki/hentoid/database/domains/Content.java
- app/src/main/java/me/devsaki/hentoid/dirpicker/events/CurrentRootDirChangedEvent.java
- app/src/main/java/me/devsaki/hentoid/dirpicker/events/UpdateDirTreeEvent.java
Fix weak warnings detected by android studio using this site as a reference
https://www.geeksforgeeks.org/java-util-objects-class-java/
obs: Content method seems wrong to just compare if their are referencing the same object or if only those two atributes from all the ones Content has are equal.
> Fix weak warnings

- app/src/main/java/me/devsaki/hentoid/parsers/content/NhentaiContent.java
the site url of nhentai books was being affected by this bug because result.setUrl using the gallery url to get it's value what this entail is the following:
-Before correction:
https://nhentai.net/g/99991/1/
became
https://nhentai.net/g/9999
-After correction:
https://nhentai.net/g/99991/1/
becomes
https://nhentai.net/g/99991/
i tested downloading books that had the code 99991, 11, 1 and the one reported by the user 176361 all of them downloaded without errors and redirected in queue and download library to the correct book.
> fixes #352

- app/src/main/res/values-ru/array_preferences.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/array_preferences.xml
- app/src/main/res/values/strings.xml
**Implements Feature:** En and Ru locales cleanup
<br />
- Added `tools:ignore="MissingTranslation"` to more strings that not necessarily need to be translated
- Marked `app_name` untranslatable
- Fixed a few comments's position
- Reverted `%%` to `%` where necessary
<br />
> Localization: Cleanup [3]

- app/src/main/res/values-fr/strings_download_service.xml
- app/src/main/res/values-it/array_preferences.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/array_plug_reactions.xml
- app/src/main/res/values/array_preferences.xml
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/strings_settings.xml
**Implements Feature:** Reformatted resource files and RU additions
<br />
- Strings marked as `translatable="false"` are moved to the easy-to-navigate `donottranslate.xml` file
- Weblate-styled comments are reverted to an easier-to-read style
- Translated language names for RU
<br />
> Localization: Reformatted resource files and RU additions

- app/src/main/AndroidManifest.xml
- app/src/main/java/me/devsaki/hentoid/activities/MissingWebViewActivity.java
- app/src/main/java/me/devsaki/hentoid/activities/SplashActivity.java
- app/src/main/java/me/devsaki/hentoid/core/HentoidApp.java
- app/src/main/res/layout/activity_missing_web_view.xml
- app/src/main/res/values-ru/array_preferences.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-ru/strings_settings.xml
- app/src/main/res/values-ru/strings_tools.xml
- app/src/main/res/values-uk/array_preferences.xml
- app/src/main/res/values-uk/strings.xml
- app/src/main/res/values-uk/strings_settings.xml
- app/src/main/res/values-uk/strings_tools.xml
- app/src/main/res/values/strings.xml
**Fixes issue** [#934](https://github.com/avluis/Hentoid/issues/934): Unhandled exception on app's startup when WebView is not available on the system
<br />
- Before any activity is even launched, `HentoidApp.java` tried to prefill user-agents by querying WebView; obviously, assuming it's present on the system and not disabled. It now throws an error into the log and ignores it, because a message will be shown to the user down the road.
- `SplashActivity` checks on its launch, whether WebView is available: if it's not, the launch halts and an error message is shown to the user instead with the explanation and advice.
Here's what the error screen looks like: 
> Unhandled exception on app's startup when WebView is not available on the system

- app/src/main/java/me/devsaki/hentoid/fragments/preferences/PreferencesFragment.kt
Fixes issue : Fix crash when clearing browser cookies
- Fix crash when doing preferences -> browser -> clear all cookies
- _CookieManager.getInstance().removeAllCookies_ is asynchronous
- So, previous code crashes because _val caption_ is not initalized before making snackbar
> Fix crash when clearing browser cookies

- app/src/main/java/me/devsaki/hentoid/activities/LibraryActivity.java
- app/src/main/java/me/devsaki/hentoid/workers/BaseWorker.java
**Fixes issue** : Fix some issues about English locale setting
<br />
- Make notification to English when English locale setting is on
- Make sure LibraryActivity to English when English locale setting is on
- Notifications and Toasts generated by BaseWorker are affected by machine's locale, NOT an app's setting.
e.g) download progress notification, "Already queued" toast.
- Sometimes the app changes its locale to machine's locale. _e.g) initWebview of BaseWebActivity.java line:270_
It affects to LibraryActivity's locale when onRestart LibraryActivity.
e.g) visit website -> back to LibraryActivity
- LibraryActivity is the only "singleTop" activity. So I override LibraryActivity's onRestart only.
<br /> …
> Fix some issues about English locale setting

- app/src/main/java/me/devsaki/hentoid/activities/BaseActivity.java
- app/src/main/java/me/devsaki/hentoid/activities/LibraryActivity.java
- app/src/main/java/me/devsaki/hentoid/util/LocaleHelper.java
- app/src/main/java/me/devsaki/hentoid/workers/BaseWorker.java
**Fixes issue** : Optimize performance of changing locale to English
<br />
- Optimize performance of changing locale to English
- There's two case before doing "changing locale"
Case 1. The app locale is already "en"
Case 2. The app locale is not "en"
- I checked the ratio of "Case 1" is pretty higher than "Case 2" before doing "changing locale"
- Optimizing idea is the app don't need to change locale if its locale is already "en"
<br />
> Optimize performance of changing locale to English

- app/src/main/assets/downloaded.css
- app/src/main/java/me/devsaki/hentoid/activities/sources/BaseWebActivity.java
- app/src/main/java/me/devsaki/hentoid/activities/sources/CustomWebViewClient.java
- app/src/main/java/me/devsaki/hentoid/activities/sources/EHentaiActivity.java
- app/src/main/java/me/devsaki/hentoid/activities/sources/ExHentaiActivity.java
- app/src/main/java/me/devsaki/hentoid/activities/sources/HitomiActivity.java
- app/src/main/java/me/devsaki/hentoid/database/CollectionDAO.java
- app/src/main/java/me/devsaki/hentoid/database/ObjectBoxDAO.java
- app/src/main/java/me/devsaki/hentoid/database/ObjectBoxDB.java
- app/src/main/java/me/devsaki/hentoid/util/Preferences.java
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings_settings.xml
- app/src/main/res/xml/preferences.xml
**Implements Feature:** Mark merged books in browser
<br />
- New feature to mark merged books in browser.
- Work like "Mark downloaded books" but display "merged" icon on the image.
- If user merges "book A" and "book B", only book A is marked as downloaded in browser.
This new feature make "book B" also marked as merged so users can notice this book is in merged book.
- "Book A" also marked as merged, not downloaded.
<br />
> Mark merged books in browsers

- app/src/main/java/me/devsaki/hentoid/activities/DuplicateDetectorActivity.kt
- app/src/main/java/me/devsaki/hentoid/fragments/tools/DuplicateMainFragment.kt
- app/src/main/res/values/strings.xml
**Implements Feature:** Show how many items are left in main page of a duplicate detector.
<br />
- Show how many items are left in main page of a duplicate detector.
- `DuplicateDetectorActivity.updateTitle` has parameter `count`
if count>0, `updateTitle` update title to "n duplicates" for the detail page
if count<0, `updateTitle` update title to "n item(s) left" for the main page
if count=0, `updateTitle` update title to "Duplicate Detector" for the main page without any items
<br />
> Duplicate detector : Show how many items are left in main page

- app/src/main/java/me/devsaki/hentoid/activities/DuplicateDetectorActivity.kt
**Fixes issue** : Fix to display a right number of items in the detail page of the duplicate detector in some situation
- Fix to display a right number of items in the detail page of the duplicate detector in some situation
- When `DuplicateDetectorActivity` changes its lifecycle from `onPause` to `onResume`
e.g) press items in the detail page and press back button, press home button and resume
- `DuplicateDetailsFragment` displays the wrong number in the title because `DuplicateDetectorActivity` has the observer.
<br />
> Duplicate detector : Fix to display a right number of items in the detail page

- app/src/main/java/me/devsaki/hentoid/fragments/intro/ImportIntroFragment.kt
**Fixes issue** : Make Coroutine works like old RxJava
<br />
- Make Coroutine works like old RxJava
- A Coroutine in `ImportIntroFragment.kt`  works slightly different way than an old RxJava (commit : e1232a982131ca331914108d04aedc5757064429 )
It makes crash when selecting empty folder as a Hentoid folder because of LifeCycle related problem.
It also makes a black screen when selecting folder already exist Hentoid folder because of `runBlocking`
e.g) An old RxJava works like 
(select folder -> back to app -> show user 'please wait' -> do next works)
A Coroutine with runBlocking works like 
(select folder -> show black screen -> back to app -> do next works)
<br />
> Make Coroutine works like old RxJava

- app/src/main/java/me/devsaki/hentoid/activities/sources/BaseWebActivity.java
- app/src/main/java/me/devsaki/hentoid/activities/sources/HitomiActivity.java
- app/src/main/java/me/devsaki/hentoid/util/Preferences.java
- app/src/main/res/layout/activity_base_web.xml
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings_settings.xml
- app/src/main/res/xml/preferences.xml
**Implements Feature:** Language filter button for Hitomi
<br />
- Language filter button helps users browse their wanted language only.
- Only works on Hitomi
- In the case user want to browse contents in English only,
3 steps was needed before
1. press right-top menu button
2. press language
3. press English  
But with Language filter button, only 1 step is needed.
- The button only visible in 1st page only to prevent disrupting browsing
e.g) visible in /artist/artistName-all.html 
invisible in /artist/artistName-all.html?page=2
- The button only visible if current url is showing "all" language contents
e.g) invisible in /artist/artistName-english.html
<br />
> Browser: Language filter button for hitomi

- app/src/main/java/me/devsaki/hentoid/activities/sources/CustomWebViewClient.java
- app/src/main/java/me/devsaki/hentoid/workers/PrimaryImportWorker.java
**Fixes issue** : Ads not filtered in some region, Custom style not loaded correctly in some sites, Importing issue
<br />
- Make if Okhttp failed to connect to the server with fast method(`getOnlineResourceFast`), reconnect with non-fast method(`getOnlineResource`)
- Use `isForMainFrame` instead of `isHtmlLoaded` to identify main page to make custom style load on main page only
- Allow the 1st page having a same url with the cover page.
- If okhttp failed to connect to server with fast method, hentoid do not filter the raw HTML.
Give one more chance with non-fast method so hentoid can filter the raw HTML
- Hentoid used `isHtmlLoaded` to identify if the url is the main page.
But `isHtmlLoaded` is not work correctly …
> Fixes : Ads not filtered in some region, Custom style not loaded correctly in some sites

- app/src/main/assets/pixiv.css
- app/src/main/assets/pixiv.js
- app/src/main/java/me/devsaki/hentoid/activities/sources/BaseWebActivity.java
- app/src/main/java/me/devsaki/hentoid/activities/sources/PixivActivity.java
- app/src/main/res/layout/activity_base_web.xml
**Implements Feature:** Support removing ad space, marking downloaded books on Pixiv, UI fix
<br />
- Hide ad space in Pixiv
- Support marking downloaded books in Pixiv
- Use backgroundTint in BottomAppBar
- Use `MutationObserver` because the images of Pixiv is loaded dynamically.
- Using `android:background` in BottomAppbar can't affect its color.(https://developer.android.com/reference/com/google/android/material/bottomappbar/BottomAppBar)
<br />
> Pixiv : Support removing ad space, marking downloaded books

- app/src/main/java/me/devsaki/hentoid/fragments/reader/ReaderImageBottomSheetFragment.kt
- app/src/main/java/me/devsaki/hentoid/util/file/FileHelper.java
It should now show more apps relevant to image and stop showing irrelevant apps in the share menu
**Implements Feature:** Show more relevant apps for image sharing, eg: Lens (for translating)
<br />
Add overloading method to shareFile to be able to change the intent typing (backward compatibility and minimizing change)
Change the share button in the viewer to use type of 'image/*' instead of 'text/*'
Regarding #504, share now include print and other apps that include feature that can turn a single image to pdf
but that's probably not the intent of #504
> Fix image sharing intent type

- app/src/main/java/me/devsaki/hentoid/util/BundleX.kt
**Reduce duplicate code by using property factory**
- Code affected should function and perform exactly as before
- No issues fixed or introduced
- No new features introduced
A bug in older Android SDKs prevented us from using method references to refer to Bundle member functions. In particular `Bundle::getBoolean` could not be referenced which prevented us from using a generic factory function that receives these method references.
Now that this issue has been fixed in newer `compileSdk`, this PR aims to improve code readability while maintaining functionality.
A **Rebase and Merge** is recommended when accepting this pull request to keep git history neat.
> BundleX.kt cleanup

- app/src/main/assets/downloaded.css
- app/src/main/java/me/devsaki/hentoid/activities/sources/BaseWebActivity.kt
- app/src/main/java/me/devsaki/hentoid/activities/sources/CustomWebViewClient.kt
- app/src/main/java/me/devsaki/hentoid/activities/sources/EHentaiActivity.kt
- app/src/main/java/me/devsaki/hentoid/activities/sources/ExHentaiActivity.kt
- app/src/main/java/me/devsaki/hentoid/activities/sources/HitomiActivity.kt
- app/src/main/java/me/devsaki/hentoid/database/CollectionDAO.kt
- app/src/main/java/me/devsaki/hentoid/database/DatabaseMaintenance.kt
- app/src/main/java/me/devsaki/hentoid/database/ObjectBoxDAO.kt
- app/src/main/java/me/devsaki/hentoid/database/ObjectBoxDB.kt
- app/src/main/java/me/devsaki/hentoid/util/Preferences.java
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings_settings.xml
- app/src/main/res/xml/preferences.xml
**Implements Feature:** Mark queued books in browser
- New feature to mark queued books.
- Remove orphan queue first to prevent NPE
- Remove orphan queue before calling `selectQueueContents` to prevent NPE
<br />
> Browser : Mark queued books
