avluis/Hentoid

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/me/devsaki/hentoid/AppLockActivity.java
- app/src/main/java/me/devsaki/hentoid/ImporterActivity.java
- app/src/main/java/me/devsaki/hentoid/MainActivity.java
- app/src/main/java/me/devsaki/hentoid/MessageSupportActivity.java
- app/src/main/java/me/devsaki/hentoid/PreferencesActivity.java
- app/src/main/java/me/devsaki/hentoid/components/HentoidActivity.java
- app/src/main/res/layout/activity_app_lock.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/strings_settings.xml
Here are my changes - what do you think?
> More tweaks.

- app/src/main/java/me/devsaki/hentoid/DownloadsActivity.java
- app/src/main/res/values/strings.xml
Please be sure to check I didn't screw anything up.
These are for issue https://github.com/csaki/Hentoid/issues/8 and https://github.com/csaki/Hentoid/issues/9 .
> Fixes for issue 8 & 9.

- app/src/main/AndroidManifest.xml
- app/src/main/java/me/devsaki/hentoid/DownloadsActivity.java
- app/src/main/java/me/devsaki/hentoid/PreferencesActivity.java
Improve pagination performance in Download list.
Working up/home button in PreferenceActivity.
Please check that I have not broken the app for older devices.
> Download list performance improvement & Pref tweaks.

- app/src/main/AndroidManifest.xml
- app/src/main/java/me/devsaki/hentoid/ContentListActivity.java
- app/src/main/java/me/devsaki/hentoid/DownloadsActivity.java
- app/src/main/java/me/devsaki/hentoid/MainActivity.java
- app/src/main/java/me/devsaki/hentoid/PreferencesActivity.java
- app/src/main/java/me/devsaki/hentoid/adapters/ContentAdapter.java
- app/src/main/java/me/devsaki/hentoid/database/HentoidDB.java
- app/src/main/java/me/devsaki/hentoid/database/domains/Content.java
- app/src/main/java/me/devsaki/hentoid/database/enums/AttributeType.java
- app/src/main/java/me/devsaki/hentoid/database/enums/Site.java
- app/src/main/java/me/devsaki/hentoid/database/enums/StatusContent.java
- app/src/main/java/me/devsaki/hentoid/parser/HitomiParser.java
- app/src/main/java/me/devsaki/hentoid/service/DownloadManagerService.java
- app/src/main/java/me/devsaki/hentoid/util/Helper.java
- app/src/main/java/me/devsaki/hentoid/util/HttpClientHelper.java
- app/src/main/java/me/devsaki/hentoid/util/NetworkStatus.java
- app/src/main/res/drawable/image_button.xml
- app/src/main/res/layout/row_download.xml
- app/src/main/res/xml/preferences.xml
Addressing issue: https://github.com/csaki/Hentoid/issues/14
> Disable webView longClick

- app/build.gradle
- app/src/main/java/me/devsaki/hentoid/HentoidApplication.java
- app/src/main/java/me/devsaki/hentoid/components/HentoidActivity.java
- app/src/main/java/me/devsaki/hentoid/updater/UpdateCheck.java
- update.json
Don't throw exception if networkInfo reports "Network is not connected".
> Allow mobile data (for now) for updater.

- update.json
Just to test this new feature.
> Setting versionCode +1 in order to check updater.

- app/build.gradle
- app/src/main/java/me/devsaki/hentoid/HentoidApplication.java
- app/src/main/res/layout/activity_hentoid.xml
- app/src/main/res/values/strings_navigation_drawer.xml
- app/src/main/res/values/strings_settings.xml
> Prefs: updates over mobile data.

- app/build.gradle
In order to distribute latest apk
> Bump versionCode in app.

- app/build.gradle
- app/src/main/java/me/devsaki/hentoid/AboutActivity.java
- app/src/main/res/layout/activity_about.xml
- app/src/main/res/values/strings.xml
- update.json
> More info on the About page.

- app/src/main/java/me/devsaki/hentoid/parser/FakkuParser.java
> Fixed cover image not downloading

- app/src/main/java/me/devsaki/hentoid/database/HentoidDB.java
- app/src/main/java/me/devsaki/hentoid/database/domains/ImageFile.java
- app/src/main/java/me/devsaki/hentoid/service/DownloadManagerService.java
- app/src/main/java/me/devsaki/hentoid/util/Helper.java
> Minor cleanup and 1 bugfix

- app/src/androidTest/java/me/devsaki/hentoid/db/TestHentoidDB.java
- app/src/main/java/me/devsaki/hentoid/AppLockActivity.java
- app/src/main/java/me/devsaki/hentoid/DownloadsActivity.java
- app/src/main/java/me/devsaki/hentoid/HentoidApplication.java
- app/src/main/java/me/devsaki/hentoid/PreferencesActivity.java
- app/src/main/java/me/devsaki/hentoid/SelectFolderActivity.java
- app/src/main/java/me/devsaki/hentoid/SplashActivity.java
- app/src/main/java/me/devsaki/hentoid/abstracts/BaseWebActivity.java
- app/src/main/java/me/devsaki/hentoid/adapters/ContentAdapter.java
- app/src/main/java/me/devsaki/hentoid/adapters/ContentDownloadManagerAdapter.java
- app/src/main/java/me/devsaki/hentoid/components/HentoidActivity.java
- app/src/main/java/me/devsaki/hentoid/components/HentoidFragment.java
- app/src/main/java/me/devsaki/hentoid/database/HentoidDB.java
- app/src/main/java/me/devsaki/hentoid/database/domains/Content.java
- app/src/main/java/me/devsaki/hentoid/database/domains/ContentV1.java
- app/src/main/java/me/devsaki/hentoid/database/enums/AttributeType.java
- app/src/main/java/me/devsaki/hentoid/database/enums/Site.java
- app/src/main/java/me/devsaki/hentoid/parser/HitomiParser.java
- app/src/main/java/me/devsaki/hentoid/parser/NhentaiParser.java
- app/src/main/java/me/devsaki/hentoid/parser/TsuminoParser.java
- app/src/main/java/me/devsaki/hentoid/util/AndroidHelper.java
- app/src/main/java/me/devsaki/hentoid/util/AttributeMap.java
- app/src/main/java/me/devsaki/hentoid/util/Helper.java
this build has passed smoke testing
> Performance focused improvements

- app/src/main/java/me/devsaki/hentoid/activities/TsuminoActivity.java
- app/src/main/java/me/devsaki/hentoid/util/Helper.java
Bug caused by cloudlfare services
Re-implemented download cookie handling,
Added http response check
Passed smoke test.
> Tsumino fix

- app/src/main/java/me/devsaki/hentoid/activities/ImporterActivity.java
- app/src/main/java/me/devsaki/hentoid/activities/SelectFolderActivity.java
- app/src/main/java/me/devsaki/hentoid/adapters/ContentAdapter.java
- app/src/main/java/me/devsaki/hentoid/adapters/ContentQueueAdapter.java
- app/src/main/java/me/devsaki/hentoid/components/HentoidActivity.java
- app/src/main/java/me/devsaki/hentoid/components/ImageDownloadBatch.java
- app/src/main/java/me/devsaki/hentoid/components/ImageDownloadTask.java
- app/src/main/java/me/devsaki/hentoid/service/DownloadService.java
- app/src/main/java/me/devsaki/hentoid/util/AndroidHelper.java
- app/src/main/java/me/devsaki/hentoid/util/Helper.java
- app/src/main/java/me/devsaki/hentoid/util/HttpClientHelper.java
- app/src/main/res/layout/include_nav_drawer.xml
- app/src/main/res/values-w820dp/dimens.xml
- app/src/main/res/values/dimens.xml
Organized utility classes to correspond to their function and requirements.
Added padding to navigation drawer.
> Additional tweaks

- app/src/main/java/me/devsaki/hentoid/service/DownloadService.java
- app/src/main/java/me/devsaki/hentoid/service/NotificationPresenter.java
- app/src/main/res/values/strings_download_service.xml
> Implemented NotificationPresenter class

- build.gradle
- circle.yml
Updated Circle CI build tools to latest and reconfigured for artifact collection.
> Updated Circle CI config

- app/src/main/java/me/devsaki/hentoid/adapters/ContentAdapter.java
- app/src/main/java/me/devsaki/hentoid/fragments/DownloadsFragment.java
- app/src/main/java/me/devsaki/hentoid/listener/ItemClickListener.java
- app/src/main/res/values/strings.xml
**Implements multi item delete on Content Adapter.**
<br />
_Make sure to squash when merging_
> Multiple item deletion

- README.md
- app/build.gradle
- app/src/main/assets/nhentai/main_js.js
- build.gradle
Update JavaScript for nhentai.
Update gradle build tools.
Update Analytics.
<br />
> Update nhentai JS & project

- app/build.gradle
- app/src/main/java/me/devsaki/hentoid/activities/BaseWebActivity.java
- app/src/main/java/me/devsaki/hentoid/activities/IntroActivity.java
- app/src/main/java/me/devsaki/hentoid/database/domains/Content.java
- app/src/main/java/me/devsaki/hentoid/parsers/HentaiCafeParser.java
- app/src/main/java/me/devsaki/hentoid/parsers/HitomiParser.java
- app/src/main/java/me/devsaki/hentoid/services/DownloadService.java
- app/src/main/java/me/devsaki/hentoid/services/ImageDownloadBatch.java
- circle.yml
- Fix Hitomi Parser.
- Fix Hentai Café Parser & add support for multi-chapter works.
-
- Update build tools.
- Update AppIntro library.
- Added debug logic for parser debugging without triggering downloads.
- Testing `semaphore.release()` on a `SocketTimeoutException` in `ImageDownloadBatch.java`.
<br />
> Merge dev branch

- app/src/main/java/me/devsaki/hentoid/AnalyticsTrackers.java
- app/src/main/java/me/devsaki/hentoid/HentoidApp.java
- app/src/main/java/me/devsaki/hentoid/util/LogHelper.java
> Minor cleanup

- app/src/main/java/me/devsaki/hentoid/activities/ImportActivity.java
- app/src/main/java/me/devsaki/hentoid/fragments/EndlessFragment.java
- app/src/main/java/me/devsaki/hentoid/util/FileHelper.java
- Fix unreadable book after import 
- Avoid app crashes when displaying / accessing unexisting folders 
- Fix double book display after import
> Fix unreadable book after import + double display after import

- app/src/main/java/me/devsaki/hentoid/util/ConstsPrefs.java
- app/src/main/java/me/devsaki/hentoid/util/FileHelper.java
- app/src/main/res/values/array_preferences.xml
Change default behavior from asking every time to using default image viewer.
> Change default behavior when opening a Doujinshi

- app/src/main/java/me/devsaki/hentoid/activities/BaseWebActivity.java
- app/src/main/java/me/devsaki/hentoid/activities/ImportActivity.java
- app/src/main/java/me/devsaki/hentoid/database/domains/Content.java
- app/src/main/java/me/devsaki/hentoid/database/domains/ContentV1.java
- app/src/main/java/me/devsaki/hentoid/util/FileHelper.java
- Fix import from previous libraries (JSONv1 & JSONv2)
- Fix unreadable books after download
> Fix import from previous libraries + fix unreadable books after download

- app/src/main/AndroidManifest.xml
- app/src/main/java/me/devsaki/hentoid/activities/ASMHentaiActivity.java
- app/src/main/java/me/devsaki/hentoid/activities/PururinActivity.java
- app/src/main/java/me/devsaki/hentoid/parsers/ASMHentaiParser.java
- Support for comics.asmhentai.net
- Filter ad sources from ASMhentai and Pururin
> Support for comics.asmhentai.net / Filter ad sources from ASM and Pururin

- app/src/main/java/me/devsaki/hentoid/parsers/HentaiCafeParser.java
Fix 2 crashes on HentaiCafe parser
> Fix 2 crashes on HentaiCafe parser

- app/src/main/java/me/devsaki/hentoid/adapters/ContentAdapter.java
- app/src/main/java/me/devsaki/hentoid/adapters/QueueContentAdapter.java
- app/src/main/java/me/devsaki/hentoid/database/domains/Content.java
- app/src/main/java/me/devsaki/hentoid/util/FileHelper.java
Fix bug when all the pictures of the library disappear, caused by deleting a book that hadn't been downloaded yet (with no existing download folder, which caused the app to try and clean the root folder of all albums....)
> Fix "library disappearance" bug

- app/src/main/java/me/devsaki/hentoid/activities/websites/ASMHentaiActivity.java
- app/src/main/java/me/devsaki/hentoid/activities/websites/HentaiCafeActivity.java
- app/src/main/java/me/devsaki/hentoid/activities/websites/HitomiActivity.java
- app/src/main/java/me/devsaki/hentoid/activities/websites/NhentaiActivity.java
- app/src/main/java/me/devsaki/hentoid/activities/websites/PururinActivity.java
- app/src/main/java/me/devsaki/hentoid/activities/websites/TsuminoActivity.java
- app/src/main/res/values/strings.xml
Display toaster instead of crashing when gallery is unparsable
> Display toaster instead of crashing when gallery is unparsable

- app/build.gradle
- app/src/main/java/me/devsaki/hentoid/abstracts/DownloadsFragment.java
- app/src/main/java/me/devsaki/hentoid/activities/ImportActivity.java
- app/src/main/java/me/devsaki/hentoid/database/SearchContent.java
- app/src/main/java/me/devsaki/hentoid/util/FileHelper.java
- app/src/main/java/me/devsaki/hentoid/util/FileUtil.java
- Fix random crash at startup on Android 4.4+ (linked to new search menu)
- Fix Hentoid unable to manage library in SD card subfolders (old bug present since v1.2.1)
> Fixes for startup and SD card subfolder support

- app/src/main/java/me/devsaki/hentoid/abstracts/DownloadsFragment.java
- app/src/main/java/me/devsaki/hentoid/adapters/ContentAdapter.java
- app/src/main/java/me/devsaki/hentoid/fragments/EndlessFragment.java
- app/src/main/java/me/devsaki/hentoid/fragments/PagerFragment.java
- app/src/main/java/me/devsaki/hentoid/parsers/HitomiParser.java
- app/src/main/java/me/devsaki/hentoid/services/ContentDownloadService.java
- app/src/main/java/me/devsaki/hentoid/services/RequestQueueManager.java
- app/src/main/java/me/devsaki/hentoid/ui/CarouselDecorator.java
- app/src/main/java/me/devsaki/hentoid/util/Preferences.java
- app/src/main/res/layout-v21/include_downloads_toolbar.xml
- app/src/main/res/layout/include_downloads_toolbar.xml
- app/src/main/res/layout/item_pagecarousel.xml
- app/src/main/res/values/array_preferences.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/strings_settings.xml
- app/src/main/res/xml/preferences.xml
- Integration of carousel number picker in paged view bottom toolbar
- Update Hitomi parser to new rules (again)
- Configurable number of worker threads for Volley
> Carousel page selector + update Hitomi + configurable Volley threads

- app/src/main/java/me/devsaki/hentoid/database/constants/ContentTable.java
- app/src/main/java/me/devsaki/hentoid/database/domains/Content.java
- app/src/main/java/me/devsaki/hentoid/enums/Site.java
- app/src/main/java/me/devsaki/hentoid/parsers/PururinParser.java
- Adapt Pururin parser to new site layout 
- Clarify arguments in DB query
> Adapt Pururin parser to new site layout 

- app/src/main/java/me/devsaki/hentoid/abstracts/DownloadsFragment.java
- app/src/main/java/me/devsaki/hentoid/database/HentoidDB.java
- app/src/main/java/me/devsaki/hentoid/database/domains/Content.java
- app/src/main/java/me/devsaki/hentoid/parsers/BaseParser.java
- app/src/main/java/me/devsaki/hentoid/util/FileHelper.java
- Fix crash when coverUrl is empty 
- Fix crash when tag button not found 
- Fix cases when Content.getAuthor would return null
> Multiple fixed for crashes in 1.3.9 (Firebase)

- app/src/main/java/me/devsaki/hentoid/HentoidApp.java
- app/src/main/java/me/devsaki/hentoid/abstracts/DownloadsFragment.java
- app/src/main/java/me/devsaki/hentoid/activities/ImportActivity.java
- app/src/main/java/me/devsaki/hentoid/adapters/ContentAdapter.java
- app/src/main/java/me/devsaki/hentoid/database/HentoidDB.java
- app/src/main/java/me/devsaki/hentoid/database/constants/ImageFileTable.java
- app/src/main/res/xml/preferences.xml
- build.gradle
- Fix crash when choosing download root folder in prefs (missing key)
- Fix duplicate book displays in library view
- Fix library view not refreshing after importing one's own root folder (e.g. after a file transfer)
- Fix attempt at CursorWindowAllocationException reported by Firebase by creating a DB index
> Misc. fixes

- app/src/main/java/me/devsaki/hentoid/HentoidApp.java
- app/src/main/java/me/devsaki/hentoid/abstracts/DownloadsFragment.java
- app/src/main/java/me/devsaki/hentoid/activities/ImportActivity.java
- app/src/main/java/me/devsaki/hentoid/adapters/ContentAdapter.java
- app/src/main/java/me/devsaki/hentoid/database/HentoidDB.java
- app/src/main/java/me/devsaki/hentoid/database/constants/ImageFileTable.java
- app/src/main/java/me/devsaki/hentoid/util/FileHelper.java
- app/src/main/res/xml/preferences.xml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
don't mind the back and forth between gradle versions
> Fix for File.toPath issue (firebase)

- app/src/main/AndroidManifest.xml
- app/src/main/java/me/devsaki/hentoid/abstracts/DownloadsFragment.java
- app/src/main/java/me/devsaki/hentoid/activities/IntentActivity.java
- app/src/main/java/me/devsaki/hentoid/adapters/ContentAdapter.java
- app/src/main/java/me/devsaki/hentoid/collection/mikan/MikanAccessor.java
- app/src/main/java/me/devsaki/hentoid/database/DatabaseAccessor.java
- app/src/main/java/me/devsaki/hentoid/listener/AttributeListener.java
- app/src/main/java/me/devsaki/hentoid/listener/ContentListener.java
- app/src/main/java/me/devsaki/hentoid/services/ContentDownloadService.java
- app/src/main/res/layout/activity_about.xml
- app/src/main/res/layout/fragment_downloads.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/theme.xml
- app/src/main/res/xml/app_tracker.xml
- Fix sticky notification when download canceled
- Restore and comment IntentActivity 
- Fix pink font in prefs menu
- Mikan view : Clarify errors in toaster 
- Fix components order so that empty text & loading text do not appear in front of the search panel
> Rescue fixes for Mikan

- app/src/main/java/me/devsaki/hentoid/services/ImportService.java
- app/src/main/java/me/devsaki/hentoid/util/FileHelper.java
**Implements Feature:** recursive search for library import
<br />
- importing a library will now handle sub directories
<br />
> added recursive JSON search to import from sub directories

- app/src/main/java/me/devsaki/hentoid/HentoidApp.java
- app/src/main/java/me/devsaki/hentoid/abstracts/DownloadsFragment.java
- app/src/main/java/me/devsaki/hentoid/activities/ImportActivity.java
- app/src/main/java/me/devsaki/hentoid/activities/bundles/SearchActivityBundle.java
- app/src/main/java/me/devsaki/hentoid/activities/sources/BaseWebActivity.java
- app/src/main/java/me/devsaki/hentoid/adapters/ContentAdapter.java
- app/src/main/java/me/devsaki/hentoid/adapters/ImagePagerAdapter.java
- app/src/main/java/me/devsaki/hentoid/adapters/QueueContentAdapter.java
- app/src/main/java/me/devsaki/hentoid/collection/LibraryMatcher.java
- app/src/main/java/me/devsaki/hentoid/collection/mikan/MikanCollectionAccessor.java
- app/src/main/java/me/devsaki/hentoid/database/DatabaseMaintenance.java
- app/src/main/java/me/devsaki/hentoid/database/HentoidDB.java
- app/src/main/java/me/devsaki/hentoid/database/ObjectBoxCollectionAccessor.java
- app/src/main/java/me/devsaki/hentoid/database/ObjectBoxDB.java
- app/src/main/java/me/devsaki/hentoid/database/domains/Content.java
- app/src/main/java/me/devsaki/hentoid/fragments/SearchBottomSheetFragment.java
- app/src/main/java/me/devsaki/hentoid/parsers/EHentaiParser.java
- app/src/main/java/me/devsaki/hentoid/parsers/HentaiCafeParser.java
- app/src/main/java/me/devsaki/hentoid/parsers/NexusParser.java
- app/src/main/java/me/devsaki/hentoid/parsers/content/EHentaiGalleriesMetadata.java
- app/src/main/java/me/devsaki/hentoid/parsers/content/MusesContent.java
- app/src/main/java/me/devsaki/hentoid/parsers/content/PururinContent.java
- app/src/main/java/me/devsaki/hentoid/services/DatabaseMigrationService.java
- app/src/main/java/me/devsaki/hentoid/services/ImportService.java
Fix a group of issues reported by Sonar.
> Fix issues reported by Sonar

- app/build.gradle
- app/src/main/java/me/devsaki/hentoid/activities/SearchActivity.java
- app/src/main/java/me/devsaki/hentoid/database/CollectionDAO.java
- app/src/main/java/me/devsaki/hentoid/database/ObjectBoxDAO.java
- app/src/main/java/me/devsaki/hentoid/fragments/SearchBottomSheetFragment.java
- app/src/main/java/me/devsaki/hentoid/listener/ResultListener.java
- app/src/main/java/me/devsaki/hentoid/viewmodels/SearchViewModel.java
- app/src/main/java/me/devsaki/hentoid/viewmodels/ViewModelFactory.kt
- app/src/test/java/me/devsaki/hentoid/viewmodels/SearchViewModelTest.kt
- custom callbacks were removed and simplified by using RxJava instead
- new ViewModelFactory which is responsible for creating custom ViewModels and supplying their dependencies
- SearchViewModel constructor now receives an instance of CollectionDAO instead of creating one
- SearchBottomSheetFragment and SearchActivity ViewModel provider now uses ViewModelFactory for ViewModel creation
- Added a simple test for SearchViewModel
Typically ViewModels are behavior tested by providing mocks for their dependencies then verifying state by inspecting the values of their LiveDatas. Ideally the test class should mimic the behavior of the view by calling the viewmodel's public methods in order.
A special JUnit rule `InstantTaskExecutorRule` is also needed to make LiveData work in a test context …
> Search vm refactor for testing

- app/src/main/res/values/array_splash_quotes.xml
Whenever submitting a PR, please follow this template and replace anything that does not apply -- remove this text before submitting.
**Fixes issue** #<issue_number> or **Implements Feature:** [describe feature or link to discussion]
<br />
-
-
-
-
-
-
<br />
> Eny please dont be stupid 1

- app/build.gradle
- app/src/main/java/me/devsaki/hentoid/activities/Api29MigrationActivity.java
- app/src/main/java/me/devsaki/hentoid/fragments/library/LibraryContentFragment.java
- app/src/main/java/me/devsaki/hentoid/widget/DragSelectTouchListener.java
- app/update.json
- Fix ScrollerCompat deprecations in DragSelectTouchListener
- Fix onActivityResult deprecations
- onRequestPermissionsResult is also deprecated, but I didn't do that one because the implementation of permission requesting around the project was a bit confusing.
> Fix some deprecations

- app/src/main/res/values-ru/array_plug_reactions.xml
- app/src/main/res/values-ru/array_preferences.xml
- app/src/main/res/values-ru/array_splash_quotes.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-ru/strings_download_service.xml
- app/src/main/res/values-ru/strings_settings.xml
- app/src/main/res/values-ru/strings_slides.xml
- app/src/main/res/values-ru/strings_tools.xml
**Implements Feature:** Adds Russian translation
<br />
- The new `values-ru` folder contains all strings that could be (and have been) localized to Russian.
- If Russian is on the list of languages that the user has set in the OS (but not below English, because then the English strings would be preferred), they’re going to see the app in its localized version.
<br />
> Localization: Russian

- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-ru/strings_download_service.xml
- app/src/main/res/values-ru/strings_settings.xml
**Implements Feature:** Polishing up Russian localization
<br />
- Finishing touches on the localization
<br />
> RU localization: cleaning up

- app/src/main/res/values-ru/array_preferences.xml
- app/src/main/res/values-ru/array_splash_quotes.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-ru/strings_settings.xml
- app/src/main/res/values-ru/strings_slides.xml
- app/src/main/res/values/array_preferences.xml
- app/src/main/res/values/array_splash_quotes.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/strings_download_service.xml
- app/src/main/res/values/strings_settings.xml
- app/src/main/res/values/strings_slides.xml
**Implements Feature:** En and Ru locales cleanup
<br />
- Style and terminology are now (hopefully) consistent and fully done
- (Hopefully) all characters needed escaping are now escaped
- Other minor improvements
<br />
> Localization: Cleanup

- app/src/main/java/me/devsaki/hentoid/database/domains/ErrorRecord.java
- app/src/main/java/me/devsaki/hentoid/enums/ErrorType.java
- app/src/main/java/me/devsaki/hentoid/fragments/queue/ErrorStatsDialogFragment.java
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-nb-rNO/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
**Implements Feature:** Support for localized error types
<br />
- Localized error types are shown only in the UI
<br />
> Localizing error types

- app/src/debug/res/values/strings.xml
- app/src/main/res/values-es/array_url_blacklist.xml
- app/src/main/res/values-es/array_url_whitelist.xml
- app/src/main/res/values-fr/array_url_blacklist.xml
- app/src/main/res/values-fr/array_url_whitelist.xml
- app/src/main/res/values-hu/array_url_blacklist.xml
- app/src/main/res/values-hu/array_url_whitelist.xml
- app/src/main/res/values-hu/strings_settings.xml
- app/src/main/res/values-it/array_url_blacklist.xml
- app/src/main/res/values-it/array_url_whitelist.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-it/strings_settings.xml
- app/src/main/res/values-nb-rNO/array_url_blacklist.xml
- app/src/main/res/values-nb-rNO/array_url_whitelist.xml
- app/src/main/res/values-nb-rNO/strings.xml
- app/src/main/res/values-nb-rNO/strings_settings.xml
- app/src/main/res/values-ru/array_preferences.xml
- app/src/main/res/values-ru/array_url_blacklist.xml
- app/src/main/res/values-ru/array_url_whitelist.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-ru/strings_settings.xml
- app/src/main/res/values/array_url_blacklist.xml
- app/src/main/res/values/array_url_whitelist.xml
**Implements Feature:** Fixup for [Reformatted resource files and RU additions](https://github.com/avluis/Hentoid/pull/935)
<br />
> Fixup for Reformatted resource files and RU additions

- app/src/main/res/values-ru/array_splash_quotes.xml
- app/src/main/res/values-ru/strings.xml
**Implements Feature:** RU localization quickfix
<br />
- Nothing much really
<br />
> RU localization: quickfix

- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-uk/strings.xml
**Implements Feature:** RU and UK localization: finishing touches for 1.16
> RU and UK localization: finishing touches for 1.16

- app/src/main/java/me/devsaki/hentoid/activities/sources/HitomiActivity.java
Whenever submitting a PR, please follow this template and replace anything that does not apply -- remove this text before submitting.
**Fixes issue** : Hitomi white page bug
<br />
- Fix hitomi white page bug
<br />
> Fix hitomi white page bug

- app/src/main/java/me/devsaki/hentoid/activities/sources/HitomiActivity.java
**Fixes issue** : remove ads in Hitomi
<br />
- Remove ads in the detail page of Hitomi
<br />
> Hitomi : remove ads

- app/src/main/assets/downloaded.css
- app/src/main/java/me/devsaki/hentoid/activities/sources/BaseWebActivity.java
- app/src/main/java/me/devsaki/hentoid/activities/sources/CustomWebViewClient.java
- app/src/main/java/me/devsaki/hentoid/activities/sources/HitomiActivity.java
- app/src/main/java/me/devsaki/hentoid/enums/Site.java
- app/src/main/java/me/devsaki/hentoid/json/core/JsonSiteSettings.java
- app/src/main/java/me/devsaki/hentoid/util/ContentHelper.java
- app/src/main/java/me/devsaki/hentoid/util/Preferences.java
- app/src/main/res/raw/sites.json
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings_settings.xml
- app/src/main/res/xml/preferences.xml
**Implements Feature:** Mark Books with blocked tags.
<br />
- New feature to mark books with blocked tags.
- Works on hitomi, hentai2read, hdporncomics, multporn
<br />
> Browser : Mark books with blocked tags

- app/src/main/java/me/devsaki/hentoid/activities/sources/CustomWebViewClient.java
**Fixes issue** : Mark books with blocked tags : Work with new simplifyUrl
<br />
- Mark books with blocked tags is not working after refactoring `simplifyUrl` 
a373b6e453626b9fbf24bc4c38f16b2eb66f719f
<br />
> Mark books with blocked tags : Work with new simplifyUrl
